- TombEngine/Objects/TR3/Entity/tr3_monkey.cpp
If monkey is triggered, this is normally not Laras enemy.
So this condition creature->Enemy->IsLara() cant work, because creature->Enemy was previously set to nullptr which results to an uncatched exception
> Fix Monkey Crash when Monkey is triggered

- TombEngine/Objects/Generic/Doors/double_doors.cpp
- TombEngine/Objects/Generic/Doors/underwater_door.cpp
Underwater and double doors now can't still be interacted even if they are opened
> Fix Underwaterdoor, Fix Doubledoors

- Documentation/Changes.txt
- TombEngine/Game/collision/collide_room.cpp
This PR fixes occasional wrong slope calculations when climbing up a ledge, and possibly some other collision issues, because newly introduced `Location` field is only immediately updated one when dealing with Lara in `GetCollisionInfo`. `item->RoomNumber` is not updated immediately and postponed until next control loop - therefore, when `SetPosition` animcommand is called, slopes for old room are passed by `GetCollisionInfo` function.
This is a very ancient issue which originates from the fact that original code used globals for getting slope values, which in turn were updated by `GetFloorHeight` function, which got completely refactored in TEN.
I need explicit approval from @asasas9500 on this change, because it involves systemic changes in `GetCollisionInfo` behaviour.
> Use Location->RoomNumber for all GetCollisionInfo calculations for Lara

- Documentation/Changes.txt
- TombEngine/Game/camera.cpp
- TombEngine/Game/collision/collide_item.cpp
- TombEngine/Game/room.cpp
- TombEngine/Game/room.h
- TombEngine/Objects/TR3/Vehicles/kayak.cpp
- TombEngine/Objects/TR3/Vehicles/minecart.cpp
- TombEngine/Renderer/Renderer11Compatibility.cpp
- TombEngine/Sound/sound.cpp
This pull request fixes several problems with flipmaps, namely "ghost" static mesh collision, light spilling from flipped to unflipped room, and several issues with object collision handling.
Complementary [changes to TE](https://github.com/MontyTRC89/Tomb-Editor/tree/filtered_flipped_rooms) are needed, otherwise correct behaviour is not guaranteed.
> Filter out invisible flipped rooms in various parts of game code

- TombEngine/Game/Lara/lara.cpp
- TombEngine/Game/Lara/lara.h
- TombEngine/Game/Lara/lara_struct.h
- TombEngine/Game/camera.cpp
- TombEngine/Game/control/control.cpp
- TombEngine/Game/control/control.h
- TombEngine/Game/effects/simple_particle.cpp
- TombEngine/Game/effects/simple_particle.h
- TombEngine/Game/gui.cpp
- TombEngine/Game/health.cpp
- TombEngine/Game/health.h
- TombEngine/Game/savegame.cpp
- TombEngine/Game/spotcam.cpp
- TombEngine/Game/spotcam.h
- TombEngine/Renderer/Renderer11.h
- TombEngine/Renderer/Renderer11Draw.cpp
- TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.cpp
- TombEngine/Specific/Input/Input.cpp
- TombEngine/Specific/Input/Input.h
- TombEngine/Specific/level.cpp
- TombEngine/Specific/savegame/flatbuffers/ten_savegame_generated.h
- TombEngine/Specific/savegame/schema/ten_savegame.fbs
Decopypastes `DoTitle` and `DoLevel` control routines and merges them into single `DoLevel` routine. Also refactors inconsistent underlying methods as well.
Additionally, allows to spawn "real" Lara in title flyby, which means she can be killed and can interact with room geometry and objects.
**Things to test**
1) Do new game / new game with level select / load game from title menu.
2) Do load game from in-game.
3) Exit game from title and from in-game.
4) Enter / exit inventory and try to use various items from it.
5) Check if any weird things are happening in any of these cases during gameplay (object activation, Lara controls, triggers).
6) Test how Lara works in title level (`Flow.EnableLaraInTitle(true)` command in Gameflow.lua)
> Unify DoTitle and DoLevel

- Documentation/Changes.txt
- TombEngine/Specific/Input/Input.cpp
For example, now, when you will reassign jump key to a draw weapon key or vice versa, jump and draw weapon won't happen at the same time.
> Fix conflicting default vs non-default controls overlapping each other

- TombEngine/Game/Lara/lara.h
- TombEngine/Game/animation.cpp
- TombEngine/Game/animation.h
- TombEngine/Game/collision/collide_room.h
- TombEngine/Game/control/box.cpp
- TombEngine/Game/control/control.h
- TombEngine/Game/itemdata/itemdata.h
- TombEngine/Objects/TR5/Object/tr5_pushableblock.cpp
- TombEngine/Objects/TR5/Object/tr5_pushableblock.h
- TombEngine/Objects/TR5/Object/tr5_pushableblock_info.h
New constants are +1 or -1 block +/- Lara's bounding box Z2 value at the very last frame of the pushing/pulling animation. Ideally it could even be fetched from the animation itself rather than typing it in the code.
Now the block follows Lara's hands as expected, stops when it should, and stops exactly at the center of the block at the end of Lara's pulling or pushing animation.
Should be used with attached animations below.
- Also includes fixed versions of the ungrab animations.
- Also includes possibility to ungrab earlier when Lara has just started grabbing the block.
[PUSHABLE_ANIMATIONS.zip](https://github.com/MontyTRC89/TombEngine/files/10251906/PUSHABLE_ANIMATIONS.zip)
> Fix offset for pushing and pulling a block

- TombEngine/Objects/TR4/Entity/tr4_setha.cpp
now the correct mesh appears on seth normal attacks and the big blue spiky ball.
> fix seth flameball missile mesh

- Documentation/Changes.txt
- TombEngine/Objects/TR1/Entity/tr1_big_rat.cpp
It was happening, that when the Big Rat was killed, like other objects, "CreatureAnimation( )" puts the monster in deactivate state and deletes its item->Data.
But the Control function was trying to access that item->Data after that. In the "IsRatOnWater( )" function, which must be activated after CreatureAnimation( ). Because item->Data didn't exist by then, the game crashes.
This fix what it does is add a check verification to IsRatOnWater in the area that uses creature so if it detects that item->Data is invalid, it ignores those lines.
> Fix Big Rat death crash

- TombEngine/Objects/Generic/generic_objects.cpp
Although the trapdoor code were correct, looks like that at some moment, someone merged all the trapdoors to initialize them together with the same values.
But Ceiling and Floor Trapdoors must use Collision functions different than the normal trapdoor. So this fix separate those objects from the generic trapdoors and put their right collision functions.
(P.D, I found an ID_SCALING_TRAPDOOR, I don't know what is that, so I write its initialization block like a normal trapdoor but I commented it, whoever created may know what to do with it.).
> Fix: Ceiling and Floor trapdoors

- Documentation/Changes.txt
- TombEngine/Game/collision/collide_room.cpp
- TombEngine/Objects/TR3/Entity/tr3_tiger.cpp
- TombEngine/Objects/TR4/Entity/tr4_harpy.cpp
- TombEngine/Objects/TR5/Entity/tr5_lion.cpp
This branch make some light changes to Tigers and Lions to improve their behaviour.
- Changed the ranges of the melee attacks, so now it does both bites animation (looks like a combo), although if it gets Lara against a wall, may do only the quick one. Or if lara is a bit far, he may do the jumping one.
- When the tiger is running but Lara is stopped, I added a probability condition, to incentivate the swipe attack over the melee bites.
- If while running, Tiger decides he won't make the melee attack, now there is another condition to check that Lara is ahead before do the swipe attack, (to reduce the number of missdirected attacks), so if lara is not in front, tiger will keep running.
- Separated the melee attacks states from the swipe attack state. (Because some are done with mouth …
> Tiger polishment adngel

- TombEngine/Objects/TR5/Entity/tr5_guard.cpp
- TombEngine/Objects/TR5/Entity/tr5_guard.h
- TombEngine/Objects/TR5/tr5_objects.cpp
fixed slots: (also added headshot instant death to these objects)
ID_SNIPER
ID_MAFIA
ID_MAFIA2
ID_SWAT
ID_GUARD1
ID_GUARD2
ID_GUARD3
> fixed #995 explodeable headmeshes for TR5 guards

- TombEngine/Math/Random.cpp
- TombEngine/Math/Random.h
- Fix random direction generation function having a bias toward cube corners.
- Fix point in sphere generation function having a bias toward positions closer to the centre of the sphere.
- Add `GeneratePoint2DInSquare()`.
- Add `GeneratePoint2DInCircle()`.
- Add `GeneratePointOnSphere()`.
> Fix direction generation

- Documentation/Changes.txt
- TombEngine/Game/gui.cpp
- TombEngine/Renderer/Renderer11DrawMenu.cpp
- TombEngine/Scripting/Internal/LanguageScript.h
- TombEngine/Specific/Input/Input.cpp
- TombEngine/Specific/Input/Input.h
Adds "Reset to defaults" menu to control configuration menu.
Additionally, either when resetting to defaults or launching TEN for the first time, automatically binds XBOX mapping instead of keyboard mapping, if XBOX controller is connected. Keyboard mapping remains active in such case too, as it implicitly works as a primary layout.
Things to test:
- Whether key bindings are assigned correctly on first TEN launch (delete `HKCU/Software/TombEngine` in registry to test).
- Whether keyboard layout is correctly reset to defaults.
- Whether XBOX binding is applied when resetting layout to defaults in menu.
- Whether XBOX binding is correct (test with XBOX controller).
> Default input bindings

- Documentation/Changes.txt
- TombEngine/Game/control/control.cpp
- TombEngine/Game/gui.cpp
- TombEngine/Game/gui.h
- TombEngine/Sound/sound.cpp
- TombEngine/Sound/sound.h
- TombEngine/Specific/winmain.cpp
Stops all current sounds when entering either inventory or pause menu.
Additionally stops all current soundtracks when entering pause menu (like in PSX versions of the game).
Additionally plays menu sound when entering both pause and inventory menu for consistency.
> Pause sounds in menus

- TombEngine/Specific/Input/Input.cpp
The default behaviour of the OIS library used here (for some inexplicable reason) blocks standard operation of the Windows key. This restores the regular behaviour, since it is a common combination hotkey to use Win+Shift+Arrow keys to quickly move windows around multi-monitor displays.
> Use OIS ParamList since default behaviour blocks the WIN key.

- Documentation/Changes.txt
- TombEngine/Objects/TR2/Entity/tr2_knife_thrower.cpp
Knife thrower never called CreatureActive function, meaning it never got a priority value, meaning it never updated its target position.
Closes #1099
> Knife thrower fix

- TombEngine/Objects/Generic/Traps/crumblingPlatform.cpp
- TombEngine/Objects/Generic/Traps/crumblingPlatform.h
- TombEngine/Objects/Generic/generic_objects.cpp
- TombEngine/TombEngine.vcxproj
I wrote some code for crumbling platform object.
It has 3 ocb functions.
- OCB == 0: Default behaviour. The platform will start to shake when Lara steps in and will crumble during 35 frames (The animation's leght).
- OCB > 0: The platform will start to shake when Lara steps  and will crumble during the number of frames indicated in the OCB.
- OCB < 0: The platform will need be activated with a trigger, then it will crumble during the number of frames indicated in the OCB.
Right now it needs some changes to the object in the WAD.
- The crumbling animation by default is connecting to the falling animation when it ends, that unables the platform to keep crumbling for more than 35 frames. So this version has changed that to allow the crumbling animation loop.
- The original bounding box …
> Adngel crumbling platform

- Documentation/Changes.txt
- TombEngine/Game/Setup.cpp
- TombEngine/Game/control/box.cpp
- TombEngine/Game/room.cpp
- TombEngine/Game/room.h
- TombEngine/Objects/TR4/Entity/Wraith.cpp
Fixes an issue with incorrectly switching room while using `SetPos()` script function, if flipped room is available at that position.
Additionally, this PR introduces small flipmap refactor to better reflect used data types.
> Flipmap fixes

- TombEngine/Game/control/trigger.cpp
- TombEngine/Game/control/volume.cpp
- TombEngine/Game/control/volume.h
- TombEngine/Game/control/volumeactivator.h
- TombEngine/Game/savegame.cpp
- TombEngine/Scripting/Internal/ReservedScriptNames.h
- TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.cpp
- TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.h
- TombEngine/Specific/level.cpp
This PR introduces a way to access node events compiled into level file from lua API. It is done by searching whole node event array by the name and finding a node event with same name. Eventually, this PR also allows to access node events from another node events, therefore allowing to do nested calls and for loops via nodes.
To test:
- Calling node events from lua by name
- Check if existing volumes work correctly (because the way event is accessed was changed too)
> Allow to access node events from scripting

- TombEngine/Game/Lara/lara.cpp
- TombEngine/Game/room.cpp
- TombEngine/Game/room.h
- Fix room number neighbor getter wrongly returning neighbors beyond the appropriate search depth.
- Use `std::swap()` when flipping rooms instead of making temp copies.
- Add comments, streamline code.
> Room fixes

- Documentation/Changes.txt
- TombEngine/Game/Lara/lara_initialise.cpp
- TombEngine/Game/Lara/lara_initialise.h
- TombEngine/Game/control/control.cpp
- TombEngine/Game/control/flipeffect.cpp
- TombEngine/Game/control/trigger.cpp
- TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.cpp
- TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.h
Implements missing functionality for LARA_START_POS object.
Now, if there are any LARA_START_POS objects in newly loaded level, engine will search for such object with OCB similar to optionally provided start position index either in timer field for legacy triggers, or in additional argument for lua script function.
Additionally, this PR fixes issue with legacy leveljump trigger which ignored both provided level index and timer value for start position index.
> Lara start position handling

- TombEngine/Objects/TR5/Trap/LaserBeam.cpp
The light from the laser beams spawned in all color spectrums as soon as Lara touched the laser beams. This bug has been fixed.
> Hotfix laserbeam color

- CHANGELOG.md
- TombEngine/Scripting/Internal/ReservedScriptNames.h
- TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.cpp
- TombEngine/Scripting/Internal/TEN/Objects/Room/RoomObject.cpp
- TombEngine/Scripting/Internal/TEN/Objects/Room/RoomObject.h
https://discord.com/channels/1072511394735464498/1073914803711660112/1278842042469842996
- The function Room:GetRoomNumber() returns the room ID (int) of an object of type room. This function is essential for the `Create moveable` node.
- The GetReverbType() method has been corrected. The ScriptReserved variable was incorrect
- Modified `Moveable()` function description for consistency
> Add Room:GetRoomNumber() method

- TombEngine/Game/items.h
- TombEngine/Objects/Generic/Object/objects.cpp
- TombEngine/Objects/TR1/Entity/SkateboardKid.cpp
- TombEngine/Objects/TR2/Entity/tr2_skidman.cpp
- TombEngine/Objects/TR2/Entity/tr2_spear_guardian.cpp
- TombEngine/Objects/TR2/Entity/tr2_sword_guardian.cpp
- TombEngine/Objects/TR3/Entity/Shiva.cpp
- TombEngine/Objects/TR4/Entity/tr4_dog.cpp
- TombEngine/Objects/TR4/Entity/tr4_mummy.cpp
- TombEngine/Objects/TR4/Entity/tr4_skeleton.cpp
- TombEngine/Objects/TR4/Trap/tr4_cog.cpp
- TombEngine/Objects/TR5/Entity/tr5_larson.cpp
N/A
Reported by @Lwmte 
The bitwise operation for item.Status dont make sense, so i removed that and remplaced it with correct value.
> Fixed bitwise for itemStatus

- CHANGELOG.md
- TombEngine/Game/control/control.cpp
- TombEngine/Game/gui.cpp
- TombEngine/Game/savegame.cpp
- TombEngine/Game/savegame.h
N/A
Alters the behaviour of game loop after player death:
- If any key except Esc key is pressed after death delay has passed, load game dialog is invoked.
- If Esc key is pressed after death delay has passed, game goes back to title, as always.
Load game dialog is only invoked if there are any valid savegames in any slot. Otherwise, game always goes back to title.
> Load after death

- CHANGELOG.md
- Documentation/doc/2 classes/Objects.Moveable.html
- TombEngine/Scripting/Internal/ReservedScriptNames.h
- TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.cpp
- TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.h
N/A
Adds `Moveable:GetTargetState()` to the Lua API to retrieve the *target* state of a moveable.
The API only had `Moveable:GetState()`, which refers to the *current* state.
> Expose moveable's target state to Lua API

- TombEngine/Game/camera.cpp
- TombEngine/Game/camera.h
- TombEngine/Objects/TR4/Trap/tr4_teethspike.cpp
- TombEngine/Objects/TR5/Object/tr5_rollingball.cpp
This PR addresses a camera bug occurring when Lara dies on a slope, causing a glitched, bouncing behavior. The issue originates from commit 53a7797.
That commit intended to fix camera behavior during special death animations. The camera code was refreshing the camera values on every frame, overwriting the specific values set for special death animations. To prevent this, that commit added a condition checking if Lara was alive before overwriting the Chase camera values. However, due to the lack of refreshing, this caused the default Chase camera to behave incorrectly when Lara died without triggering a special camera. (Like the camera bouncing when Lara dies on slopes).
This PR refines the conditions for camera refresh control. Now, it will ignore camera refreshing not only when Lara is …
> Adngel fix death camera

- CHANGELOG.md
- Documentation/doc/1 modules/Effects.html
- TombEngine/Scripting/Internal/ReservedScriptNames.h
- TombEngine/Scripting/Internal/TEN/Effects/EffectsFunctions.cpp
N/A
This exposes to Lua the **wind vector** that was applied to the current frame by the engine.
This allows applying the same wind (or an altered version of it) to a custom object, or even Lara herself (for example if she's using a parachute).
I named the branch `expose_weather_parameters` in case other things related to weather come to mind (for example the wind's base strength, and direction, and maybe even overwriting them), but the PR is ready to use as-is otherwise.
_Feel free to amend the description in the doc, I'm not convinced myself with it!_
> Expose wind

- TombEngine/Objects/TR5/Emitter/Waterfall.cpp
Removed the values "orient2" and "origin2" because it is already set with "pos".
The higher the density value, the thinner the waterfall, and lower values ​​make a thicker waterfall so I changed the name of the value "density" into "sparseness".
> Waterfall emitter formatting fix

- TombEngine/Renderer/RendererHelper.cpp
- TombEngine/framework.h
Modified the screenshot filename format to ensure chronological and alphabetical sorting.
Updated the date format from DD-MM-YYYY-HH-MM-SS to YYYYMMDD_  followed by a millisecond-based timestamp, appending just the last 5 digits for proper sorting,
Example:
Before: TEN-03-03-2025-14-30-15.png
After: TEN-20250303_98765.png -- Last digits vary based on exact capture moment
> Sort Screenshots by YYYYMMDD #1372

- CHANGELOG.md
- Documentation/doc/3 primitive classes/Rotation.html
- TombEngine/Scripting/Internal/ReservedScriptNames.h
- TombEngine/Scripting/Internal/TEN/Types/Rotation/Rotation.cpp
- TombEngine/Scripting/Internal/TEN/Types/Rotation/Rotation.h
N/A
Fixes an issue with `Rotation` class, which was using non-intuitive range from -180 degrees to 180 degrees instead of 0-360 degrees. Additionally implements `Rotation:Signed()` method which returns signed angle, in case it is still needed. Also corrects and introduces angle wrapping where it is needed.
> Fixed rotation class to use 0-360 degree range

- CHANGELOG.md
- Scripts/Settings.lua
- TombEngine/Game/Lara/lara_fire.cpp
- TombEngine/Game/control/los.cpp
- TombEngine/Game/control/los.h
- TombEngine/Game/people.cpp
- TombEngine/Scripting/Internal/ReservedScriptNames.h
- TombEngine/Scripting/Internal/TEN/Flow/Settings/Settings.cpp
- TombEngine/Scripting/Internal/TEN/Flow/Settings/Settings.h
N/A
Prevents player from targeting enemies, if they are occluded by moveables and static meshes. Moveables and static meshes with small collision boxes are ignored.
> Object targeting occlusion
