TombEngine/Scripting/Internal/ReservedScriptNames.h, TombEngine/Scripting/Internal/TEN/Misc/Miscellanous.cpp
it is now possible to trigger / untrigger a flipmap in Lua.
To trigger a flipmap use the lua function
FlipMap(ID) while ID is the ID of Flipmap in TombEditor
If FlipMap was triggered a second call will untrigger the Flipmap
=> Add FlipMap function to Lua

TombEngine/Objects/TR5/Object/tr5_rollingball.cpp
If Rollingball has OCB 1 the rollingball is silent. No Sounds and no Camera Shaking
=> Rollingball with OCB 1 is silent

TombEngine/Scripting/Internal/ReservedScriptNames.h, TombEngine/Scripting/Internal/TEN/Misc/Miscellanous.cpp
Use this in Lua Script:
EnableFlyBy(ID of FlyBy)
=> Lua Function for enable FlyBy's

Documentation/Changes.txt, TombEngine/Game/effects/effects.cpp
If waterfallmist is enabled you can now disable it with antitrigger
=> Add Antitrigger function to waterfallmists

Documentation/Changes.txt, TombEngine/Game/Lara/lara_basic.cpp, TombEngine/Objects/TR4/Object/tr4_sarcophagus.cpp, TombEngine/Objects/TR4/Object/tr4_sarcophagus.h, TombEngine/Objects/TR4/Object/tr4_sas_drag_bloke.cpp, TombEngine/Objects/TR4/Object/tr4_sas_drag_bloke.h, TombEngine/Objects/TR4/tr4_objects.cpp, TombEngine/TombEngine.vcxproj
=> Sas drag bloke implementation

TombEngine/Game/Lara/lara_fire.cpp, TombEngine/Game/control/los.cpp, TombEngine/Game/control/volume.h, TombEngine/Game/items.cpp, TombEngine/Game/items.h, TombEngine/Game/savegame.cpp, TombEngine/Objects/Sink.h, TombEngine/Scripting/Internal/TEN/Objects/Camera/CameraObject.cpp, TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.cpp, TombEngine/Scripting/Internal/TEN/Objects/ObjectsHandler.cpp, TombEngine/Scripting/Internal/TEN/Objects/ObjectsHandler.h, TombEngine/Scripting/Internal/TEN/Objects/Sink/SinkObject.cpp, TombEngine/Scripting/Internal/TEN/Objects/SoundSource/SoundSourceObject.cpp, TombEngine/Sound/sound.h, TombEngine/Specific/LevelCameraInfo.h, TombEngine/Specific/level.cpp
Puts all Lua callback names into substruct and simplfies their names.
=> Simple Lua callback refactor

Documentation/Changes.txt, TombEngine/Objects/TR2/tr2_objects.cpp
killer statue's setup stuff was missing hence it was not triggering, please check thoroughly in case I havem't duplicated or anything lol
=> add killer statue setup

TombEngine/Game/camera.cpp, TombEngine/Game/camera.h, TombEngine/Scripting/Internal/ReservedScriptNames.h, TombEngine/Scripting/Internal/TEN/Misc/Miscellanous.cpp, TombEngine/Scripting/Internal/TEN/Objects/Lara/LaraObject.cpp, TombEngine/Scripting/Internal/TEN/Objects/Lara/LaraObject.h, TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.cpp, TombEngine/Scripting/Internal/TEN/Objects/Moveable/MoveableObject.h, TombEngine/Scripting/Internal/TEN/Objects/ObjectsHandler.cpp
Moveable:AttachCamera(camMeshId, cameraTargetObject, targetMeshId) //Attach the game camera to any moveables (Moveable) mesh (camMeshId) and the camera target to any moveables (cameraTargetObject) mesh (targetMeshID).
Lara:UndrawWeapons() --usable with Lara as moveable //Lara will undraw her weapons if they are drawn, throw away flare if she helds one in her hand.
Lara:ThrowawayTorch() --usable with Lara as moveable //Lara will throw away the torch if she helds one in her hand.
Lara:GetHandStatus() --usable with Lara as moveable //Returns 0=HandsFree, 1=Busy(climbing,etc), 2=WeaponDraw, 3=WeaponUndraw, 4=WeaponInHand.
Lara:GetWeaponType() --usable with Lara as moveable //Returns 0=None, 1=Pistols, 2=Revolver, 3=Uzi, 4=Shotgun, 5=HK, 6=Crossbow, 7=Flare, 8=Torch, 9=GrenadeLauncher, …
=> lua-functions-moved-to-lara-class

Documentation/Changes.txt, Scripts/Gameflow.lua, TombEngine/Game/control/trigger.cpp, TombEngine/Game/control/trigger.h, TombEngine/Game/pickup/pickup.cpp, TombEngine/Game/pickup/pickup.h, TombEngine/Objects/TR4/Object/tr4_sarcophagus.cpp, TombEngine/Scripting/Include/Flow/ScriptInterfaceFlowHandler.h, TombEngine/Scripting/Internal/ReservedScriptNames.h, TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.cpp, TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.h
Introduces `Flow.EnableMassPickup(true)` option in Gameflow.lua to enable/disable mass pickup.
=> Enable mass pickup

Documentation/Changes.txt, TombEngine/Game/animation.cpp, TombEngine/Game/animation.h, TombEngine/Game/effects/effects.cpp, TombEngine/Game/effects/effects.h, TombEngine/Game/effects/smoke.cpp, TombEngine/Game/effects/spark.cpp, TombEngine/Game/effects/spark.h, TombEngine/Game/effects/tomb4fx.h, TombEngine/Game/effects/weather.cpp, TombEngine/Math/Random.cpp, TombEngine/Math/Random.h, TombEngine/Objects/TR1/Trap/DamoclesSword.cpp, TombEngine/Objects/TR4/Entity/tr4_harpy.cpp, TombEngine/Objects/TR4/Entity/tr4_setha.cpp, TombEngine/Objects/TR4/Entity/tr4_setha.h, TombEngine/Objects/TR5/Entity/tr5_roman_statue.cpp
fixed enemies: seth and harphy
=> refractored charging sparks and charging fire for enemies

TombEngine/Scripting/Internal/ReservedScriptNames.h, TombEngine/Scripting/Internal/TEN/Objects/Lara/LaraObject.cpp, TombEngine/Scripting/Internal/TEN/Objects/Lara/LaraObject.h
Check for GetTorchIsLit(bool) to determine if lara hold a lit torch or not
=> Lua - TorchIsLit

TombEngine/Game/Lara/lara_one_gun.cpp, TombEngine/Game/effects/effects.cpp, TombEngine/Game/effects/effects.h, TombEngine/Objects/TR4/Entity/tr4_guide.cpp, TombEngine/Objects/TR4/Entity/tr4_knight_templar.cpp, TombEngine/Objects/TR4/tr4_objects.cpp
added sparks, 
he can now destroy static meshes up to slot 50, 
fixed crash when he attacks
=> fix-TR4-knight-templar

Documentation/Changes.txt, TombEngine/Game/effects/spark.cpp, TombEngine/Game/effects/spark.h, TombEngine/Game/itemdata/creature_info.h, TombEngine/Game/items.cpp, TombEngine/Objects/TR3/Entity/tr3_cobra.cpp, TombEngine/Objects/TR5/Entity/tr5_cyborg.cpp
Fixed a crash with TriggerSparks, however I changed his electric sparks to that cool yellow dot shaped sparks again.
Fixed water death. 
Fixed meshswap. 
Now he switches to escape mood when the room is gassed. 
He is now invincible when Lara shoots at him. (there was a bug that he didn't do anything once he had 0 hp).
=> Fixed TR5 Cyborg

TombEngine/Game/control/los.cpp
fixed explodableMeshbits
fixed that undead enemies could get damage
=> fixed explodableMeshbits

TombEngine/Game/effects/tomb4fx.cpp
SFX_TR4_DEMIGOD_SIREN_SWAVE is the OG sound
=> fixed Shockwave sfx to SFX_TR4_DEMIGOD_SIREN_SWAVE

TombEngine/Game/Lara/lara_fire.cpp, TombEngine/Game/Lara/lara_fire.h, TombEngine/Game/control/box.cpp, TombEngine/Game/control/box.h, TombEngine/Game/items.cpp, TombEngine/Game/items.h, TombEngine/Objects/TR2/Entity/tr2_spear_guardian.cpp, TombEngine/Objects/TR2/Entity/tr2_yeti.cpp, TombEngine/Objects/TR3/Entity/tr3_shiva.cpp, TombEngine/Objects/TR3/Entity/tr3_shiva.h, TombEngine/Objects/TR3/tr3_objects.cpp, TombEngine/Objects/TR4/Entity/tr4_baddy.cpp, TombEngine/Objects/TR4/Entity/tr4_baddy.h, TombEngine/Objects/TR4/Entity/tr4_big_scorpion.cpp, TombEngine/Objects/TR4/tr4_objects.cpp, TombEngine/Objects/TR5/Entity/tr5_roman_statue.cpp, TombEngine/Objects/TR5/Entity/tr5_roman_statue.h, TombEngine/Objects/TR5/tr5_objects.cpp, TombEngine/Specific/setup.cpp, TombEngine/Specific/setup.h, TombEngine/TombEngine.vcxproj
- Removed hack for baddy2 and roman_god1/2
=> Added obj->HitRoutine

TombEngine/Objects/Effects/Boss.cpp
added enchanged explosion effect, max shockwave angle is 24 now
=> Fix puna boss dead smoke crash

Documentation/Changes.txt, TombEngine/Game/Lara/lara_one_gun.cpp, TombEngine/Game/effects/spark.cpp, TombEngine/Game/effects/spark.h, TombEngine/Game/items.cpp, TombEngine/Game/items.h, TombEngine/Objects/TR3/Entity/PunaBoss.cpp, TombEngine/Objects/TR5/Entity/tr5_roman_statue.cpp
- Added possibility to remove entity getting fire when shooted by explosive projectile !
=> Fixed fire damage on puna

TombEngine/Game/effects/effects.cpp, TombEngine/Game/effects/effects.h, TombEngine/Objects/Effects/Boss.cpp, TombEngine/Objects/Effects/Boss.h, TombEngine/Objects/TR3/Entity/PunaBoss.cpp, TombEngine/Objects/TR3/Entity/SophiaLeigh.cpp
useful for Puna, Sophia and Tony boss explosions.  (main color zero means normal explosion)
=> added individual explosion color

TombEngine/Game/savegame.cpp, TombEngine/Scripting/Include/Objects/ScriptInterfaceObjectsHandler.h, TombEngine/Scripting/Include/ScriptInterfaceGame.h, TombEngine/Scripting/Include/VarMapVal.h, TombEngine/Specific/level.cpp, TombEngine/TombEngine.vcxproj
This change also makes the project perfectly compilable for C++20, everything works just fine.
=> Removed redefinition of VarMapMal and moved it to VarMapVal.h. 

Documentation/Changes.txt, TombEngine/Shaders/DX11_Inventory.fx, TombEngine/Shaders/Math.hlsli, TombEngine/Shaders/ShaderLight.hlsli
This fixes the z-fighting issue in the inventory, but fixes directional lighting as well
=> Fixing shaders for lighting and inventory

TombEngine/Objects/TR4/Entity/Wraith.cpp, TombEngine/Objects/TR4/Object/WraithTrap.cpp
Wraith trap has to be a nullmesh object. (Animating10 from catacomb.wad)
=> removed wraith trap animations

TombEngine/TombEngine.vcxproj
Fixed the version needed to compile the project in Visual Studio 2019
=> Visual Studio 2019 solution

TombEngine/Scripting/Internal/ReservedScriptNames.h, TombEngine/Scripting/Internal/TEN/Strings/DisplayString/DisplayString.cpp, TombEngine/Scripting/Internal/TEN/Strings/DisplayString/DisplayString.h, TombEngine/Scripting/Internal/TEN/Strings/StringsHandler.cpp, TombEngine/Scripting/Internal/TEN/Strings/StringsHandler.h
The **string:SetTranslated()** method sets the translated parameter. 
If it is true, this will be the key string for the translation that will be displayed. If it is false, this will be the string that will be displayed.
The **isStringDisplaying()** function checks whether the string is displayed.
It returns the bool true if it is shown, false if it is hidden.
=> String:SetTranslated() method and isStringDisplaying() function.

TombEngine/Game/control/trigger.cpp, TombEngine/Objects/Generic/puzzles_keys.cpp, TombEngine/Objects/Generic/puzzles_keys.h
use a switch trigger for the keyhole to make it multi useable. Lara will get the key back into her inventory after using it. (only with switch triggers)
Using key animation = ocb number
=> multiusable keyholes

TombEngine/Game/control/control.cpp, TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.cpp
Check if there is the title and at least one playable level to avoid crashing the game
=> Check levels in Gameflow.lua

TombEngine/Game/Lara/lara_tests.cpp, TombEngine/Game/collision/collide_room.cpp, TombEngine/Game/control/los.cpp, TombEngine/Game/control/trigger.cpp, TombEngine/Game/effects/effects.cpp, TombEngine/Game/effects/tomb4fx.cpp, TombEngine/Game/room.cpp, TombEngine/Objects/Effects/flame_emitters.cpp, TombEngine/Objects/Generic/Object/rope.cpp, TombEngine/Objects/TR4/Vehicles/motorbike.cpp, TombEngine/Objects/TR5/Entity/tr5_submarine.cpp, TombEngine/Objects/Utils/object_helper.cpp, TombEngine/Renderer/Renderer11Draw.cpp, TombEngine/Renderer/Renderer11Frame.cpp, TombEngine/Specific/level.cpp, TombEngine/TombEngine.vcxproj
Resolves potential problems with incorrect bitwise operator precedence.
=> Resolve compiler warning 4554

Documentation/Changes.txt, TombEngine/Objects/TR5/Object/tr5_raisingblock.cpp
* Only shakes it if OCB is not zero
* Simplifies shaking procedure
* Removes abandoned commented code
=> Raising block fixes

Documentation/Changes.txt, TombEngine/Game/control/control.cpp, TombEngine/Game/gui.cpp, TombEngine/Game/gui.h, TombEngine/Game/savegame.cpp, TombEngine/Specific/savegame/flatbuffers/ten_savegame_generated.h, TombEngine/Specific/savegame/schema/ten_savegame.fbs
* Keeps soundtrack data in savegame in a more consistent format.
* Preserves last inventory item when saving, reloading and restarting game. Prior to that, it was not resetting even if you started new game.
=> Savegame and inventory fixes

TombEngine/Game/Lara/lara_fire.cpp, TombEngine/Game/camera.cpp, TombEngine/Game/control/control.cpp, TombEngine/Game/gui.cpp, TombEngine/Renderer/RenderTarget2D/RenderTarget2D.cpp, TombEngine/Renderer/Renderer11Draw.cpp, TombEngine/Renderer/Renderer11Draw2D.cpp, TombEngine/Renderer/Renderer11DrawMenu.cpp, TombEngine/Renderer/Renderer11Helper.cpp, TombEngine/Scripting/Internal/TEN/Misc/Miscellaneous.cpp, TombEngine/Specific/Input/Input.cpp, TombEngine/Specific/configuration.cpp, TombEngine/Specific/configuration.h, TombEngine/Specific/winmain.cpp
Creates a new registry subfolder for 1.1.0 values to maintain registry compatibility with previous engine versions.
=> Update registry for 1.1.0

TombEngine/Objects/TR3/Trap/train.cpp
=> Fix animation when Lara's killed by TR3 train.

Documentation/Changes.txt
Add update about fix to the train death animation as request.
=> Add fix about train animation in log.

TombEngine/Game/Hud/PickupSummary.cpp, TombEngine/Game/Hud/PickupSummary.h, TombEngine/Scripting/Internal/TEN/Inventory/InventoryHandler.cpp
added option to display item added to inventory
https://github.com/MontyTRC89/TombEngine/assets/116632612/6025e06c-87dc-4b80-be14-392a77f8905a
=> Add display option in inventoryAdd function

TombEngine/Scripting/Internal/TEN/Inventory/InventoryHandler.cpp
=> Excess argument removed

Scripts/SystemStrings.lua, TombEngine/Game/gui.cpp, TombEngine/Scripting/Internal/LanguageScript.h
Add constant STRING_UNLIMITED to be able to translate the word "unlimited"
=> add constant "unlimited" in SystemStrings.lua

Documentation/Changes.txt, TombEngine/Scripting/Internal/ReservedScriptNames.h, TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.cpp, TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.h
function **SaveGame::DoesSaveGameExist(slot)** made available as a function lua **Flow.DoesSaveGameExist(slot)**
=> Add lua function DoesSaveGameExist()

TombEngine/Scripting/Internal/ReservedScriptNames.h, TombEngine/Scripting/Internal/TEN/DisplaySprite/ScriptDisplaySprite.cpp
- Created ScriptReserved names for get/set functions for DisplaySprite.
- Create get/set functions for DisplaySprite.
- Removed references to properties
=> Create get/set functions for DisplaySprite

TombEngine/Game/control/control.cpp, TombEngine/Game/effects/debris.cpp, TombEngine/Game/effects/debris.h, TombEngine/Game/items.cpp, TombEngine/Game/items.h, TombEngine/Renderer/Renderer11DrawEffect.cpp
Simplify debris code and possibly fix crash issues.
=> Convert debris to array

TombEngine/Game/collision/collide_room.cpp, TombEngine/Game/collision/collide_room.h, TombEngine/Objects/TR3/Trap/ElectricCleaner.cpp, TombEngine/Objects/TR3/Trap/ElectricCleaner.h, TombEngine/Objects/TR3/tr3_objects.cpp
Update of the Electric Cleaner code
- Code polishment for better standards and readibility.
- Removal of the specific pushalble HACKS, (after the pushable refactor, now the Electric Cleaner can rely in the STOPPER floor data flag to avoid the pushables).
- Removal of unused flag "DoDetectionFlag" (so the other flags have changed their bits too).
=> Electric cleaner refactor

TombEngine/Game/control/control.cpp, TombEngine/Game/control/control.h, TombEngine/Game/gui.cpp, TombEngine/Scripting/Include/Flow/ScriptInterfaceFlowHandler.h, TombEngine/Scripting/Internal/ReservedScriptNames.h, TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.cpp, TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.h, TombEngine/Scripting/Internal/TEN/Flow/GameStatuses.h, TombEngine/TombEngine.vcxproj
Implement `Flow.GetGameStatus()` function which can be useful in getting level end reason.
=> Get game status

TombEngine/Objects/TR4/Trap/SpikyWall.cpp
To stop the wall, just make a volume trigger and set the OCB of the wall to 0. To make it move again, create a volume trigger with OCB and the desired speed value.
=> Revised spiky wall

Documentation/Changes.txt, Documentation/doc/2 classes/Flow.Level.html, TombEngine/Game/Lara/lara.cpp, TombEngine/Game/Lara/lara_fire.cpp, TombEngine/Game/Lara/lara_helpers.cpp, TombEngine/Game/Lara/lara_initialise.cpp, TombEngine/Game/Lara/lara_initialise.h, TombEngine/Game/Lara/lara_one_gun.cpp, TombEngine/Game/Lara/lara_two_guns.cpp, TombEngine/Game/control/control.cpp, TombEngine/Game/control/control.h, TombEngine/Game/control/trigger.cpp, TombEngine/Game/effects/weather.cpp, TombEngine/Game/gui.cpp, TombEngine/Game/itemdata/itemdata.h, TombEngine/Game/items.cpp, TombEngine/Game/savegame.cpp, TombEngine/Game/savegame.h, TombEngine/Renderer/RendererDrawMenu.cpp, TombEngine/Scripting/Include/ScriptInterfaceLevel.h, TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.cpp, TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.h, TombEngine/Scripting/Internal/TEN/Flow/Level/FlowLevel.cpp, TombEngine/Scripting/Internal/TEN/Flow/Level/FlowLevel.h, TombEngine/Specific/level.cpp
Adds functionality similar to tomb4 hub system.
To test, create a chain of levels which may lead one to another via combination of end level triggers with specific index and LARA_START_POS objects.
To test:
- Object behaviour between levels
- Lara behaviour between levels
- Inventory state before and after leveljumps
- Saving and loading game
=> Hub system

TombEngine/Objects/TR2/Entity/tr2_skidman.cpp, TombEngine/Objects/TR2/Entity/tr2_worker_shotgun.cpp
fixes:
- TR2 Worker Shotgun: bug fix - walking shooting can hurts Lara now.
- TR2 Worker Shotgun: update - Animation and State lists included in file.
- TR2 Skidoo driver: bug fix - he will chase Lara instead of move to the map corner. https://github.com/MontyTRC89/TombEngine/issues/1187
=> Adngel small fixes

Documentation/doc/1 modules/Inventory.html, Documentation/doc/1 modules/Logic.html, TombEngine/Game/Lara/lara_helpers.cpp, TombEngine/Game/control/event.h, TombEngine/Game/control/volume.cpp, TombEngine/Game/control/volume.h, TombEngine/Game/gui.cpp, TombEngine/Game/gui.h, TombEngine/Scripting/Include/ScriptInterfaceGame.h, TombEngine/Scripting/Internal/ReservedScriptNames.h, TombEngine/Scripting/Internal/TEN/Inventory/InventoryHandler.cpp, TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.cpp, TombEngine/Scripting/Internal/TEN/Logic/LogicHandler.h
This pull request implements new `UseItem` event and `OnUseItem` level function, which allows to assign user-defined scripts or node graphs to any item used from the inventory, or remap functionality of existing items, such as medipacks or weapons.
=> UseItem event

CHANGELOG.md, TombEngine/Scripting/Internal/TEN/Objects/Volume/VolumeObject.cpp
https://discord.com/channels/1072511394735464498/1073914803711660112/1265919099377287220
Fixed Volume:GetActive() method
=> Fixed Volume:GetActive() method

CHANGELOG.md, Documentation/doc/1 modules/Flow.html, Scripts/Strings.lua, Scripts/SystemStrings.lua, TombEngine/Game/control/control.cpp, TombEngine/Game/control/control.h, TombEngine/Game/gui.cpp, TombEngine/Game/gui.h, TombEngine/Renderer/RendererDrawMenu.cpp, TombEngine/Scripting/Include/Flow/ScriptInterfaceFlowHandler.h, TombEngine/Scripting/Internal/LanguageScript.h, TombEngine/Scripting/Internal/ReservedScriptNames.h, TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.cpp, TombEngine/Scripting/Internal/TEN/Flow/FlowHandler.h
Added the ability to display "Lara's Home" entry in the main menu.
* Added `Flow.EnableHomeLevel()`
=> Add "Lara's Home" menu entry

CHANGELOG.md, TombEngine/Renderer/Renderer.h, TombEngine/Renderer/RendererDraw.cpp, TombEngine/Renderer/RendererString.cpp, TombEngine/Renderer/Structures/RendererStringToDraw.h
N/A
Support for alpha value in DisplayStrings.
=> Displaystring alpha

CHANGELOG.md, TombEngine/Renderer/RendererDrawMenu.cpp
Fixed SetIntroImagePath() not using the correct path
(replace this sentence with links to issues this PR concerns, otherwise please write "n/a")
=> Fixed SetIntroImagePath()

TombEngine/Game/Lara/lara.cpp, TombEngine/Game/Lara/lara_one_gun.cpp, TombEngine/Game/savegame.cpp, TombEngine/Math/Objects/Pose.cpp, TombEngine/Math/Objects/Pose.h, TombEngine/Objects/TR3/Entity/SophiaLeigh.cpp, TombEngine/Objects/TR4/Entity/tr4_baboon.cpp, TombEngine/Renderer/Renderer.h, TombEngine/Renderer/RendererDrawMenu.cpp, TombEngine/Renderer/RendererFrame.cpp, TombEngine/Renderer/RendererHelper.cpp, TombEngine/Renderer/RendererLara.cpp, TombEngine/Specific/savegame/flatbuffers/ten_itemdata_generated.h, TombEngine/Specific/savegame/schema/ten_itemdata.fbs
n/a
Adds functional `Scale` field to the `Pose` class. The effect is applied visually by renderer code.
=> Add `Scale` field to `Pose` class

TombEngine/Game/effects/tomb4fx.cpp, TombEngine/Objects/Effects/EmberEmitter.cpp, TombEngine/Objects/TR5/Emitter/tr5_smoke_emitter.cpp, TombEngine/Scripting/Internal/TEN/Effects/EffectsFunctions.cpp
(replace this sentence with links to issues this PR concerns, otherwise please write "n/a")
=> Fix damage Commit

CHANGELOG.md, TombEngine/Game/savegame.cpp, TombEngine/Objects/TR3/Entity/FishSwarm.cpp, TombEngine/Objects/TR3/Entity/FishSwarm.h
- [x ] I have added a changelog entry to CHANGELOG.md file on the branch/fork (if it is an internal change then it is not needed) 
- [x ] Pull request meets the Coding Conventions standards: https://github.com/MontyTRC89/TombEngine/blob/master/CONTRIBUTING.md#coding-conventions
(replace this sentence with links to issues this PR concerns, otherwise please write "n/a")
Fish emitter can now be antitriggered
=> Antitrigger fish emitter
